a=(input("enter some integars for list:"))
c=list(a.split(" "))
b=int(input("enter an number for adding with list:"))
c.append(b)
print(f'after adding a new number: {c}')
e=int(input("enter a number: "))
d=int(input("enter a index number where you want to replace by new number:"))
c.insert(d,e)
print(f'after inserting a new number:{c}')
c.pop()
print(f'after deleting last element{c}')